AstarVienna/irdb

MICADO_Sci/MICADO_Sci.yaml
Fixes some of the problems in #16
=> Add filter_file_format to MICADO_Sci.yaml

METIS/default.yaml
edited wavemax to reflect loss of Q band
=> edited wavemax to reflect the loss of Q band

METIS/METIS_DET_IFU.yaml, METIS/METIS_DET_IMG_LM.yaml, METIS/METIS_DET_IMG_N_Aquarius.yaml, METIS/METIS_DET_IMG_N_GeoSnap.yaml, METIS/default.yaml
Apply effect `AutoExposure` in METIS detectors. To test you'll need branch `oc/autodit` of Scopesim.
=> Implement AutoExposure, some cleaning

METIS/Notebooks/IMG-HL_Tau.ipynb
Please ignore/delete, just a test
=> some irrelevant changes to an outdated notebook; please delete

.github/workflows/tests.yml, HAWKI/test_hawki/test_full_package_hawki.py
Test was broken by https://github.com/AstarVienna/irdb/commit/9f24d9b4f2ed1dab7f1ad19ac9c00bf52519e644
=> Fix hawki background test

README.md
This contributing section is a copy from the proposal I just mailed. What do you think @astronomyk @oczoske @miguelverdugo
=> Add Contributing section README.md

.github/workflows/tests.yml
Run tests against dev_master and/or master
=> Second attempt to run tests against ScopeSIM master and/or dev_master

LFOA/LFOA_SBIG.yaml
Also lets see whether the CI now turns green
=> Fix x_size_unit_unit_unit_unit_unit

.github/workflows/tests.yml, requirements.github_actions.txt
=> Run notebooks in the CI

MICADO/test_micado/test_micado_imaging.py
Fixes test broken in #71 , or well, actually just makes the test less stringent so it now passes..
=> Make TestLimiting less strict

MICADO/docs/example_notebooks/1_scopesim_MCAO_4mas_galaxy-TLDR.ipynb, MICADO/docs/example_notebooks/1_scopesim_MCAO_4mas_galaxy.ipynb, MICADO/docs/example_notebooks/3_scopesim_SCAO_4mas_fv-psf.ipynb, MICADO/docs/example_notebooks/4_scopesim_SPEC_pipe_galaxy.ipynb
Use the new server in the MICADO notebooks
=> Fix MICADO notebooks

OSIRIS/code/make_maat_ifu_traces_file.py, OSIRIS/code/make_spec_trace_fits_files.py, OSIRIS/tests/test_compiles.py, OSIRIS/tests/test_maat_daves_tests.py, OSIRIS/tests/test_maat_traces.py
No functional changes. Triggered by investigation of https://github.com/AstarVienna/speXtra/pull/8
=> Cleanup OSIRIS tests

.github/workflows/tests.yml
Should move to DevOps framework soon
=> Update workflow to supported Python versions.

.gitignore
Just a straightforward addition to the .gitignore file, so I'll probably just merge it...
=> Update gitignore for Spyder etc

ELT/LIST_ELT_combined.tbl, ELT/LIST_mirrors_ELT.tbl, ELT/tests/test_TER_properties.py, METIS/LIST_METIS_mirrors_cfo.dat, MICADO/LIST_RO_SCAO_mirrors.dat, MORFEO/LIST_mirrors_morfeo_mms.tbl, _REPORTS/badge_report_log.txt, _REPORTS/badges.md, _REPORTS/badges.yaml
=> Use more specific lookup reference for default temperature

METIS/docs/example_notebooks/LSS-YSO_model_simulation.ipynb
The issue is described in #173. This will not fix it, but at least make it not fail our CI. Needs a permanent solution ASAP...
=> Patch problematic notebook

METIS/tests/test_readout_exptime.py
See https://github.com/AstarVienna/ScopeSim/issues/438
And https://github.com/AstarVienna/ScopeSim/issues/442 and https://github.com/AstarVienna/ScopeSim/issues/439
=> Test whether exptime is honored.

METIS/docs/example_notebooks/demos/demo_adc_wheel.ipynb, METIS/docs/example_notebooks/demos/demo_auto_exposure.ipynb, METIS/docs/example_notebooks/demos/demo_chopping_and_nodding.ipynb, METIS/docs/example_notebooks/demos/demo_detector_modes.ipynb, METIS/docs/example_notebooks/demos/demo_filter_wheel.ipynb, METIS/docs/example_notebooks/demos/demo_grating_efficiency.ipynb, METIS/docs/example_notebooks/demos/demo_lss_simple.ipynb, METIS/docs/example_notebooks/demos/demo_rectify_traces.ipynb, METIS/docs/example_notebooks/demos/demo_slit_wheel.ipynb
Update of the METIS demo notebooks so that they run and produce readable and useful output.
=> Update of demo notebooks

METIS/docs/example_notebooks/LSS_AGN-02_simulation.ipynb
=> Explicitly pass DIT/NDIT as None

.github/workflows/tests.yml
...to silence warnings from workflow runs.
=> Update actions versions

LFOA/tests/test_full_package_lfoa.py, LFOA/tests/test_source_shift.py, METIS/docs/example_notebooks/Introduction_to_Scopesim_for_METIS.ipynb, METIS/docs/example_notebooks/demos/demo_rectify_traces.ipynb, MICADO/docs/example_notebooks/4_scopesim_SPEC_pipe_galaxy.ipynb, WFC3/test_wfc3/test_full_package_wfc3_ir.py
This is untested; need to run the tests on github
=> download_packages instead of download_package

.github/workflows/tests.yml
=> Move condition into sister branch check to avoid empty ref name

METIS/docs/example_notebooks/METIS_WCU.ipynb
It seems we need to have the "../../../" path enabled by default and the `download_packages` disabled, otherwise it won't work in the CI (and probably on RTD).
=> Fix new WCU notebook to run in CI
