AstarVienna/irdb

Armazones/Armazones.yaml, METIS/METIS_LSS.yaml, MICADO_ETC/MICADO_ETC.yaml, MICADO_ETC/default.yaml, MICADO_Sci/MICADO_Sci.yaml, MICADO_Sci/default.yaml, Paranal/Paranal.yaml
Renamed `spectral_resolution` to `spectral_bin_width` in accord with changes made in scopesim. This frees up `spectral_resolution` to give what it promises to give, i.e. lambda/dlambda (used in `METIS_LSS.yaml`).
=> renamed spectral_resolution to spectral_bin_width

MICADO/test_micado/test_detector_array_and_traces_plot.py, irdb/publish.py
Removes the potential security bug for the IRDB packages on the unive server
Packages must now be compiles and uploaded with the addition of a password (see email conversation) by using the `-p` tag in the command line
Old: 
`$ python irdb/publish.py -cu <PKG_NAME> ... <PKG_NAME_N>`
New:
`$ python irdb/publish.py -cu <PKG_NAME> ... <PKG_NAME_N> -p <PASSWORD>`
=> removed hardcoded password. see emails

irdb/publish.py
The published packages should not contain crap like `__pycache__`, `.ipynb_checkpoints` and the like. As `shutil.make_archive` does not have the option to exclude stuff `shutil.copytree` is used to copy the package to a temporary directory, ignoring a list of `ignore_patterns` before archiving.
Also some pylint cosmetics. `compile` is a builtin and should not be used as a variable, changed to `compile_pkg` (and `upload_pkg` for symmetry). This does not affect the user interface.
=> Publish should not include __pycache__ and hidden files

MICADO/test_micado/test_detector_array_and_traces_plot.py, MICADO/test_micado/test_full_package_micado.py
This should fix all MICADO tests. Or well, `test_background_is_within_2x_of_eso_etc` is simply marked `xfail` and replaced by `test_background_is_within_4x_of_eso_etc`
This includes #44 , so maybe merge that one first
Closes #16
=> Fix all MICADO tests

irdb/publish.py, irdb/tests/test_publish.py
Improves the uploading of packages by not always updating the version.
This code will be used to upload the package for #105.
More importantly, it is a step towards creating a deployment strategy where the version is set first, and the release is created afterwards.
Furthermore, the tests are improved and now they don't pollute the local clone anymore.
=> Allow version to be read from yaml when publishing a package.

Armazones/version.yaml, ELT/version.yaml, METIS/version.yaml, MICADO/version.yaml, MORFEO/version.yaml, irdb/tests/test_publish.py
Update version files of:
- Armazones
- ELT
- METIS
- MICADO
- MORFEO
Pushed those versions to the InstPkgs server.
This should also include the corresponding tags, but since I'm pushing this from my fork, those will probably not be included. Worst case I'll add them manually afterwards...
=> 7-Eleven release

MICADO/MASK_slit_15000x20.dat, MICADO/MASK_slit_3000x16.dat, MICADO/MASK_slit_3000x48.dat, MICADO/default.yaml, MICADO/test_micado/test_micado_spec.py
- new slit mask files added for the FDR slits 3000x16, 3000x48, 15000x20 according to ELT-TRE-MCD-56300-0014_3.0
- the new slits are made available through new instrument modes defined in `default.yaml`. The old ones are still there, with a newly added deprecation notice. It would be nice if `scopesim.UserCommands` would display these.
=> make FDR slits available

MICADO/MASK_slit_15000x20.dat, MICADO/MASK_slit_15000x50.dat
As confirmed by Ric Davies, the long slit should be positioned between -5 and +10 arcsec. This closes #77 .
=> x position of long slit corrected

MICADO/FPA_array_layout.dat
This is a quick fix to #125 for the particular case of MICADO. It brings FITS keyword `EXTNAME = DETi.DATA` in line with the detector id (so that _i_ == id).
=> swapped rows 4 and 6

README.md
The Python versions badge was a bit messy, showing the whole CI matrix. The relevant information should be the versions the tests use on the `master` branch, so I limited it to that.
Also added a simple badge to check the status of our server. This might not reflect if the download is actually working, but could be a useful indication for users to see if the server is at all there, without needing to find the URL manually.
=> Add server status badge, improve python versions badge

conf.py
This will delete the `inst_pkgs` symlinks, thereby making RTD work.
However, this changes means that RTD cannot actually run the notebooks anymore. Nevertheless, for most notebooks it would probably not be possible to run them on their servers anyway. And this is better than not having documentation at all.
=> Delete symlinks before building documentation

MICADO/docs/example_notebooks/1_scopesim_MCAO_4mas_galaxy-TLDR.ipynb, MICADO/docs/example_notebooks/1_scopesim_MCAO_4mas_galaxy.ipynb
From Carmelo
> Hi. are these https://github.com/AstarVienna/irdb/tree/master/MICADO/docs/example_notebooks (dev_master) the examples that j-uwe is using? I notice that the number 1-*pynb claim to point to MCAO-MORFEO sims, however
>
>    cmd = sim.UserCommands(use_instrument="MICADO", set_modes=["SCAO", "IMG_4mas"])
>
> instead of
>
>    cmd = sim.UserCommands(use_instrument="MICADO", set_modes=["MCAO", "IMG_4mas"])
> Other issue. From the 1_scopesim_MCAO_4mas_galaxy.ipynb
>> "Download the relevant scopesim instrument packages We will need the MICADO_Sci ... "
> is not the case it uses now MICADO
Both fixed
=> Remove refence to MICADO_Sci and use MCAO where desired

.github/workflows/tests.yml, LFOA/tests/test_lfoa.py, LFOA/tests/test_source_shift.py, METIS/tests/test_metis.py, OSIRIS/tests/test_compiles.py, OSIRIS/tests/test_maat_daves_tests.py, OSIRIS/tests/test_maat_traces.py, ViennaLT/tests/test_lvilt.py, irdb/badges.py, irdb/tests/test_publish.py, pytest.ini
- Split notebook job in MICADO and METIS to run them in parallel. Setup is still copy-pasted, because caching takes too much brain to do right, and the execution time is by far dominated by the actual running of notebooks, so it doesn't matter.
- Add Python 3.12 to (non-notebook) test matrix. This actually caused one error, which is now also fixed.
- Add `slow` marker for pytest to the slowest few (non-notebook) tests, which is not currently used by the CI. Also caught one case where the `webtest` marker should have been applied, but wasn't.
- Some small improvements to make the CI runs nicer to look at.
- Prepare to do something smarter with the "Badge Report" files.
=> Run notebook tests in parallel

HAWKI/HAWKI_H2RG.yaml, METIS/METIS_DET_IFU.yaml, METIS/METIS_DET_IMG_LM.yaml, METIS/METIS_DET_IMG_N_Aquarius.yaml, METIS/METIS_DET_IMG_N_GeoSnap.yaml
`file_name` as a kwarg does seem to work, but it behaves differently from `filename`. In particular, with `file_name` the absolute path of the file is used, and with `filename` the relative path (or well, the actual given path). I have not investigated why.
The reason for harmonizing is that when generating FITS keywords, we'd like to have them to have the filename as it was given by the user or the irdb, not the absolute path where this file happens to be on this particular installation.
Do we perhaps want to force `file_name`?
E.g. put an assert in `data_container.py` instead of a fallback: https://github.com/AstarVienna/ScopeSim/blob/36df1767c2b8143a199d085cdf1af181660c058a/scopesim/effects/data_container.py#L63-L64
```python
if filename is None and "file_name" in kwargs:
filename = …
```
=> Replace file_name with filename in Effect kwargs

METIS/docs/readme.rst
Also fix package names still including directories.
=> Change `download_package` ➡️ `download_packages` in METIS documentation

MICADO/MICADO_H4RG.yaml
The SourceDescriptionFitsKeywords still cause problems, see https://github.com/AstarVienna/ScopeSim_Templates/issues/70 https://github.com/AstarVienna/ScopeSim_Templates/issues/69
=> Disble SourceDescriptionFitsKeywords for MICADO

HAWKI/test_hawki/test_full_package_hawki.py, Paranal/tests/test_paranal.py, WFC3/test_wfc3/test_full_package_wfc3_ir.py
This is in reaction to AstarVienna/Scopesim#423. Apparently I already made these changes a month ago but forgot to push them. Which lead to some minor confusion now on my end, as the local `fh/detectormanager` branch already existed and I ended up giving it the exact same name now. Anyway, I'll merge this in once it passed, because it caused ScopeSim Data to fail [today](https://github.com/AstarVienna/ScopeSim_Data/actions/runs/9729542520/job/26851563842) and [yesterday](https://github.com/AstarVienna/ScopeSim_Data/actions/runs/9721771707/job/26834885291), and the actual change has been discussed and accepted in AstarVienna/Scopesim#423.
=> Adapt to changes in ScopeSim

METIS/docs/example_notebooks/IMG_L_N-examples.ipynb, METIS/docs/example_notebooks/LSS-YSO_model_simulation.ipynb, METIS/docs/example_notebooks/LSS_AGN-01_preparation.ipynb, METIS/docs/example_notebooks/LSS_AGN-02_simulation.ipynb, MICADO/docs/example_notebooks/3_scopesim_SCAO_4mas_fv-psf.ipynb
Following AstarVienna/ScopeSim#446.
For the PSF download in MICADO, we might eventually expand the download facilities in ScopeSim, once `pooch` has proven to be (more) stable. For now, I used pooch's "script mode" to move AstarVienna/ScopeSim#332 forward.
=> Fix downloads in notebooks

METIS/docs/example_notebooks/LSS-YSO_model_simulation.ipynb
This deals with  Issue #173. 
METIS now uses by default the full non-linear spectral mappings for LSS simulations. The notebook `LSS-YSO_model_simulation.ipynb` relied on the use of the linear "science" mappings for plotting, this now necessitates an explicit rectification of the simulation results.
Currently, rectification is done as a proof of concept for the first simulation. This needs to be expanded and the notebook cleaned up before merging.
=> add rectification, needs cleaning

METIS/docs/example_notebooks/LSS-YSO_model_simulation.ipynb
Astropy units were used in this notebook in some parts, but not in others, which led to some inconsistencies. During the flux calibration, the background subtraction was scaled with the exposure time of the standard star, which I believe should not be the case. This also leads to a more realistic scaling factor in the final spectrum comparison (unless I'm missing something, scaling the source *down* to the result makes more sense, as the flux should decrease as it passes through the optical train).
Also made some plots look a little nicer and simplified some of the code.
=> Further clean up YSO notebook, apply units consistently

METIS/docs/example_notebooks/LSS_AGN-01_preparation.ipynb, METIS/docs/example_notebooks/LSS_AGN-02_simulation.ipynb
Required for AstarVienna/ScopeSim#405 to not break the METIS notebooks.
=> Supply cube as hdul and not just file name

METIS/tests/test_readout_exptime.py
The plot from here popped up during collection time (?) when running pytest locally on the whole IRDB repo. This interrupted pytest until the figure window is closed manually.
=> Set PLOTS to False

MICADO_Sci/test_micado_sci/test_micado_sci.py, MICADO_Sci/test_micado_sci/test_radiometry.py, MICADO_Sci/test_micado_sci/test_spectral_trace_files.py
These should be evaluated for their usefulness elsewhere and then moved there or deleted completely. This is a temporary solution to stop the ScopeSim_Data runs from failing.
=> Disable all tests in MICADO_Sci

setup.py
This might be able to fix the most recent ScopeSim_Data fail🤞
=> Use lxml[html_clean] instead of just lxml

HAWKI/default.yaml, LFOA/default.yaml, METIS/default.yaml, MICADO/default.yaml, MICADO_Sci/default.yaml, OSIRIS/default.yaml, ViennaLT/default.yaml, WFC3/default.yaml, docs/source/pkg_status.md, test_package/default.yaml
Corresponding ScopeSim PR coming soon.
This allows a better overview (for both developers and users) about the status of our packages and their individual modes.
This keyword is completely optional, omitting it does not result in any error.
The values intended to be used with this key and their meaning is summarized in the `pkg_status.md` guide, which becomes part of the documentation. Feedback or additions to that list are of course welcome 🙂 
To those with more "bigger picture" insight into the status of various packages and modes than myself: Please take a quick look at the statuses I used and simply request a change on this PR if you think a different one fits better for the current stage of the package or mode in question!
It is intended (at some point when there aren't as many other …
=> Add package and mode status keywords and guide

.github/workflows/tests.yml
This would avoid situations like we have in #205 (well, this wouldn't fix that one in particular, because the branch names don't match, but if they did, it would). The reverse operation (cloning the right IRDB branch into ScopeSim) needs to be done a bit differently, but this is a beginning.
For reference, I took inspiration for this from https://github.com/hse-project/hse/blob/6d5207f88044a3bd9b3539260074395317e276d5/.github/workflows/builds.yaml#L120-L148.
=> Use branch of same name in ScopeSim and Templates if exists

irdb/tests/test_package_contents.py
Relax test_default_yaml_contains_packages_list as METIS can operate without METIS
Simple 'solution' to https://github.com/AstarVienna/irdb/pull/212#issuecomment-2698016766
=> Relax test_default_yaml_contains_packages_list

METIS/METIS_WCU.yaml
This eliminates the need to load the ELT and Armazones packages when using METIS in one of the WCU modes. I also tested switching back and forth between e.g. "img_lm" and "wcu_img_lm" modes and !TEL.temperature does indeed switch as it should.
Fixes #218.
=> Override !TEL.temperature in WCU mode

.github/workflows/tests.yml, HAWKI/test_hawki/test_full_package_hawki.py, irdb/tests/test_package_contents.py, pytest.ini
No need to run those in the whole matrix, also solves the problem of multiple artifact uploads without having to use extra flags for certain matrix combination, which was the previous stopgap solution.
=> Run badge report tests separately

irdb/publish.py
=> Replace deprecated `datetime.utcnow()` in publish script

ELT/ELT.yaml, ELT/FITS_telescope_keywords.yaml, METIS/docs/example_notebooks/METIS_WCU.ipynb, METIS/headers/FITS_common_keywords.yaml
Together with @JenniferKarr and @hugobuddel we extracted the offending references in the METIS common FITS keywords file to telescope effects. These were causing METIS simulations to fail when generating WCU mode observations, because there is (quite obviously) no telescope involved in the process. 
The Gist of this PR is that TEL keywords are now contained in the ELT IRDB package.
=> Move TEL header keywords in METIS to ELT

METIS/METIS_DET_IFU.yaml, METIS/METIS_DET_IMG_LM.yaml, METIS/METIS_DET_IMG_N_GeoSnap.yaml
Implement `ADConversion` effect in METIS and MICADO. This PR accompanies https://github.com/AstarVienna/ScopeSim/pull/455.
=> ADConversion effect

METIS/tests/test_readout_exptime.py
A very similar thing occurred recently but I cannot find it right now: The code for this test was in the class body (as opposed to within a method), so it was executed during collection time and not a an actual test. Simple solution: just make it a function, it's just a single test case anyway.
=> Fix test class that should be a function

METIS/docs/example_notebooks/METIS_WCU.ipynb
I never saw plots anymore (after some update to Jupyter months ago) unless I explicitly added `plt.show()` everywhere. Finally figured out that _removing_ the `%matplotlib inline` solves that. Now I don't know if this breaks it for anyone else?
Also added the new `sim.link_irdb()`, let's see if that also works on RTD.
=> Minor cleanup in WCU notebook

METIS/METIS_DET_IFU.yaml, METIS/METIS_DET_IMG_LM.yaml, METIS/METIS_DET_IMG_N_Aquarius.yaml, METIS/METIS_DET_IMG_N_GeoSnap.yaml, METIS/tests/test_readout_exptime.py
Use `ExposureOutput` in img_lm (to be expanded to other modes), see https://github.com/AstarVienna/ScopeSim/pull/603
=> Use ExposureOutput in METIS

Armazones/version.yaml, ELT/version.yaml, HAWKI/version.yaml, LFOA/version.yaml, METIS/version.yaml, MICADO/version.yaml, MORFEO/version.yaml, Paranal/version.yaml, test_package/version.yaml
Those had been obsolete for more than one year, since we updated our release workflow. When a package is compliled to be uploaded to the server, a `version.yaml` file is created on the fly from the current timestamp and packaged in the zip file, so a package installed from the server has the version information corresponding to a tag.
But these newly created `version.yaml` files are not committed back into the repo (on purpose), so the old ones that were still there showed wildly outdated timestamps, which greatly confuses some users (see e.g. the post- merge comment in #241, although that shouldn't be _there_ but whatever) when installing from the repo.
I'm working on adding the funcitonality to `sim.bug_report()` to display a meaningful version information when a package was installed …
=> Remove all remaining `version.yaml` files

HAWKI/HAWKI_H2RG.yaml, LFOA/LFOA_SBIG.yaml, METIS/METIS_DET_IFU.yaml, METIS/METIS_DET_IMG_LM.yaml, METIS/METIS_DET_IMG_N_Aquarius.yaml, METIS/METIS_DET_IMG_N_GeoSnap.yaml, METIS/docs/example_notebooks/demos/demo_auto_exposure.ipynb, MICADO/MICADO_H4RG.yaml, MICADO_Sci/MICADO_Sci_detector.yaml, OSIRIS/OSIRIS_DET.yaml, ViennaLT/ViLT_PL16803.yaml, WFC3/WFC3_IR_DET.yaml
Implements #239. All instances of `SummedExposure` have been changed to `ExposureIntegration`. The effect name has been homogenised to `exposure_integration`.
=> Rename `SummedExposure` ➡️ `ExposureIntegration`

HAWKI/test_hawki/test_full_package_hawki.py, LFOA/tests/test_lfoa.py, ViennaLT/tests/test_lvilt.py, WFC3/test_wfc3/test_full_package_wfc3_ir.py
With optics_manager.system_transmission, in all tests that used it.
Fixes #255.
=> Replace optics_manager.surfaces_table.throughput
